2025-04-24 10:10:26,436 ERROR: Exception on /index [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 22, in index
    posts = current_user.followed_posts().paginate(
TypeError: paginate() takes 1 positional argument but 4 were given
2025-04-24 10:10:28,788 ERROR: Exception on /index [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 22, in index
    posts = current_user.followed_posts().paginate(
TypeError: paginate() takes 1 positional argument but 4 were given
2025-04-24 10:20:04,034 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:31]
2025-04-24 10:20:16,424 ERROR: Exception on /user/Haibo [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 76, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
TypeError: paginate() takes 1 positional argument but 4 were given
2025-04-24 10:20:18,312 ERROR: Exception on /explore [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 146, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
TypeError: paginate() takes 1 positional argument but 4 were given
2025-04-24 10:23:43,433 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:31]
2025-04-24 13:34:52,454 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:33]
2025-04-24 13:42:16,583 ERROR: Exception on /reset_password_request [POST] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Administrator\montyu\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Administrator\montyu\microblog\app\models.py", line 63, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2025-04-24 13:47:55,178 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:33]
2025-04-24 13:48:01,880 ERROR: Exception on /reset_password_request [POST] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Administrator\montyu\microblog\app\email.py", line 18, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2025-04-24 13:55:36,283 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:33]
2025-04-25 14:57:24,369 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:33]
2025-04-25 14:59:09,526 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:33]
2025-04-25 16:22:01,438 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
